---

# This workaround for Debian Wheezy which doesn't support ${distro_codename} macro
# See
#   https://github.com/jnv/ansible-role-unattended-upgrades/issues/19
#   https://github.com/jnv/ansible-role-unattended-upgrades/pull/20
# for details

__unattended_origins_patterns:
  - 'origin=Debian,archive=stable,label=Debian-Security'
  - 'origin=Debian,archive=oldstable,label=Debian-Security'
