---
- hosts: application
  vars:
    - certbot_auto_renew: true
    - certbot_auto_renew_user: "root"
    - certbot_auto_renew_hour: "3"
    - certbot_auto_renew_minute: "30"
    - certbot_auto_renew_options: "--quiet --no-self-upgrade"
    - certbot_create_if_missing: true
    - certbot_admin_email: aacee143-216e-43f6-87d3-4fd14fa9c07f@anonaddy.me
    - certbot_create_method: standalone
    - certbot_create_standalone_stop_services:
      - nginx
    - certbot_certs:
      - domains:
          - "{{ domain }}"

  gather_facts: no
  remote_user: root

  roles:
    - geerlingguy.certbot

